<ul>
    <li><a href=" intent://com.google.android.gms/#Intent;scheme=promote_smartlock_scheme;end">Open <img decoding="async" src="https://frpfile.com/wp-content/uploads/2021/08/system-lock-screen-icon.png" alt="Set Lock Screen" height="16" /> Set Lock Screen</a></li>
    <li><a href="intent://com.sec.android.app.samsungapps/#Intent;scheme=android-app;end">Open <img decoding="async" src="https://frpfile.com/wp-content/uploads/2020/10/galaxy-store.png" alt="Galaxy Store" height="16" /></a></li>
    <li><a href="https://galaxystore.samsung.com/detail/com.rrivenllc.shieldx?session_id=W_0a719781bf2f739158262639f4c63d35">Download <img decoding="async" loading="lazy" class="" src="https://frpfile.com/wp-content/uploads/2021/12/alliance2-e1639758859911.webp" alt="Alliance Shield" width="22" height="25" /> Alliance Shield at Galaxy Store</a></li>
    <li><a href="intent://com.rrivenllc.shieldx/#Intent;scheme=android-app;end">Open <img decoding="async" loading="lazy" class="" src="https://frpfile.com/wp-content/uploads/2021/12/alliance2-e1639758859911.webp" alt="Alliance Shield" width="22" height="25" /> Alliance Shield</a></li>
    <li><a href="intent://com.google.android.googlequicksearchbox/#Intent;scheme=android-app;end">Open <img decoding="async" src="https://frpfile.com/wp-content/uploads/2020/10/google-quick-search-box.png" alt="Google Quick Search Box" height="16" /></a></li>
    <li><a href="intent://com.android.settings/#Intent;scheme=android-app;end">Open <img decoding="async" src="https://frpfile.com/wp-content/uploads/2020/10/setting-app.png" alt="Setting App" height="16" /> <strong><span class="has-inline-color has-black-color">Setting </span></strong><span class="has-inline-color has-black-color">App</span></a></li>
    <li><a href="intent://com.google.android.youtube/#Intent;scheme=android-app;end">Open <img decoding="async" src="https://frpfile.com/wp-content/uploads/2021/12/youtube-icon.png" alt="Youtube App" height="16" /> <strong><span class="has-inline-color has-black-color">Youtube </span></strong><span class="has-inline-color has-black-color">App</span></a></li>
    <li><a href="https://galaxystore.samsung.com/detail/com.s9launcher.dir.launcher">Open <img decoding="async" src="https://frpfile.com/wp-content/uploads/2021/12/s9-launcher-icon.png" alt="S9launcher App" height="16" /> <strong><span class="has-inline-color has-black-color">S9Launcher</span></strong><span class="has-inline-color has-black-color">App</span></a></li>
    <li><a href="https://frpfile.com/wp-content/uploads/apk/Alliance%20Shield%20[App%20Manager]_0.7.54.apk">Alliance Shield.apk</a> <span style="font-family: arial, helvetica, sans-serif;"> // <a href="https://raw.githubusercontent.com/addrom/bypass/master/Alliance_Shield.apk">Link backup</a></span></li>
    <li><a href="http://www.mediafire.com/file/4ub1tavab8csp2y/FRPFILE_SMS_v2.apk/file">FRPFILE SMS v2.apk  </a></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Google_Setting.apk">Google Setting.apk </a>// <a href="https://vnrom.ondex.app/Google_Setting.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/FRP_Bypass.apk">BypassFRP-1.0.apk</a> // <a href="https://vnrom.ondex.app/FRP_Bypass.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Android_5_GAM.apk">Google-Account-Manager-5.apk</a> // <a href="https://vnrom.ondex.app/Android_5_GAM.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Android_6_GAM.apk">Google-Account-Manager-6.apk</a> // <a href="https://vnrom.ondex.app/Android_6_GAM.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Android_8-9-10_GAM.apk">Google-Account-Manager-8, 9, 10.apk</a> // <a href="https://vnrom.ondex.app/Android_8-9-10_GAM.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/QuickShortcutMaker.apk">QuickShortcutMaker 2.4.0</a> // <a href="https://vnrom.ondex.app/QuickShortcutMaker.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Apex_Launcher.apk">Apex_Launcher.apk</a> // <a href="https://vnrom.ondex.app/Apex_Launcher.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://github.com/addrom/bypass/raw/master/Smart_Switch_Mobile.apk">Smart switch.apk</a>  //  <a href="https://vnrom.ondex.app/Smart_Switch_Mobile.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Setting.apk">Setting.apk</a> // <a href="https://raw.githubusercontent.com/vnrom/bypass/master/Setting.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/Test_DPC.apk">Test_DPC.apk</a> // <a href="https://dl.ondex.app/Test_DPC.apk">Link backup</a></span></li>
    <li><span style="font-family: arial, helvetica, sans-serif;"><a href="https://raw.githubusercontent.com/vnrom/bypass/master/ES_File_Explorer.apk">ES_File_Explorer.apk</a> // <a href="https://vnrom.ondex.app/ES_File_Explorer.apk">Link backup</a></span></li>
    </ul>